[tool.poetry]
package-mode = false
name = "python-drf"
version = "0.1.0"
description = ""
authors = ["fronexxx <igorbotsii42@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.14, <4.0"
Django = "^6.0.3"
djangorestframework = "^3.17.1"
mysqlclient = "^2.2.8"
django-dotenv = "^1.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[dependency-groups]
dev = [
    "isort (>=9.0.2,<10.0.0)"
]
